const express = require("express");
const dummyText = require("./dummyText");
const writeDummy = require("./writeDummy");
const filterMidWare = require("./filterMidWare");
const countMiddleWare = require("./countMiddleWare");
const controller = require("./controller");
const sortMidWare = require("./sortMidWare");
const filterReq = require("./filterReq");
const jsonController = require("./jsonController");
const paramJson = require("./paramJson");
const app = express();
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.post("/emoji", filterMidWare, countMiddleWare, sortMidWare, controller);
app.post("/write", filterReq, jsonController);
app.post("/dummyText", filterReq, dummyText, writeDummy);
app.get("/api/:id", paramJson);
app.listen(6000, () => {
  console.log("server is listening on port 6000....");
});
