const express = require('express')
const countMiddleWare = require('../middleWare/countMiddleWare')
const filterMidWare = require('../middleWare/filterMidWare')
const sortMidWare = require('../middleWare/sortMidWare')
const { alterController } = require('../controllers/controller')
const filterReq = require('../middleWare/filterReq')
const jsonController = require('../controllers/jsonController')
const filterReqForDummyText = require('../middleWare/filterReqForDummyText')
const dummyText = require('../middleWare/dummyText')
const writeDummy = require('../controllers/writeDummy')
const paramJson = require('../controllers/paramJson')
const idParam = require('../controllers/idParam')
const charReqParam = require("../controllers/charReqParam");
const getEmoji = require('../controllers/getEmoji')
const router = express.Router()
router.route("/emoji").post(filterMidWare, countMiddleWare, sortMidWare, alterController)
router.route("/write").post(filterReq, jsonController)
router.route("/dummyText").post(filterReqForDummyText, dummyText, writeDummy)
router.route("/changeChar/:id/requests/:characters").get(paramJson)
router.route("/getOnly/:id").get(idParam)
router.route("/getOnly/:id/:charOrReq").get(charReqParam)
router.route("/emojiList").get(getEmoji)
module.exports = router